---
book_repo: pivotal-cf/docs-book-pcfservices
layout_repo: pivotal-cf/docs-layout-repo
layout_repo_ref: master

feedback_enabled: false

broken_link_exclusions: iefix|arrowhead
repo_link_enabled: true

public_host: docs.pivotal.io

elastic_search: true

sections:

# repos in org pivotal-cf: alphabetical
- repository:
    ref: '1.2'
    name: pivotal-cf/docs-scheduler
    at_path: docs-content
  directory: scheduler/1-2
  subnav_template: pcf-scheduler_subnav.erb
  product_info:
    use_local_header: true
    latest_stable_version: 1.4
    local_header_img: /images/cloud_rings.png
    local_header_title: Scheduler
    search_placeholder: Search Scheduler 1.2
    url_prefix: scheduler/1-2
    local_product_version: 1.2
    local_header_links: []
    local_header_version_list:
      - <a href="http://docs.pivotal.io/scheduler/1-4/index.html">v1.4</a>
      - <a href="http://docs.pivotal.io/scheduler/1-3/index.html">v1.3</a>
      - <a href="http://resources.docs.pivotal.io/pdfs/scheduler-1.1.pdf">v1.1</a>
      - <a href="http://resources.docs.pivotal.io/pdfs/scheduler-1.0.pdf">v1.0</a>

